name: Setup Bun
description: Set up Bun via mise and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup Tools
      uses: jdx/mise-action@v4
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
