name: Setup Toolchain
description: Set up the toolchain via mise and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup Tools
      uses: jdx/mise-action@v4
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
