name: PR continuous integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 # we don't need the history, just the latest commit - this breaks "last updated" doc pages though!

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build
